### ISSUE TITLE
SupplementBy

### ISSUE THREAD

**Issue by gharib85** [quantum-mob/Q3App#1]
Return same answer with EvenQ and OddQ

**Comment by quantum-mob** [comment]
Depending on particular input lists a and b, SupplementBy[a, b, EvenQ] and SupplementBy[a, b, OddQ] may return the same result.

Consider the example in the help documentation for SupplementBy,
SupplementBy[{5, 6, 3, 1, 2}, {4}, EvenQ].

The result is {5, 3, 1}.

To understand the above results, note that applying EvenQ on every element of the lists gives the following revised lists.

EvenQ /@ {5, 6, 3, 1, 2}  --> {False, True, False, False, True}
EvenQ /@ {4} --> {True}

Therefore, the second and last elements are removed from the first list.

----------------------------------------------------------------------------

Now, replacing function EvenQ with OddQ in the above example eventually gives the same result, but the reason behind it is different:

SupplementBy[{5, 6, 3, 1, 2}, {4}, OddQ] --> {5, 3, 1}

In this case, OddQ yields the following revised lists.

OddQ /@ {5, 6, 3, 1, 2} --> {True, False, True, True, False}
OddQ /@ {4} --> {False}

Therefore, again, the second and last elements are removed from the first list, leading to the same result.
